name: Release And Update
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Release Debug APK
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Debug APK
        run: ./gradlew clean assembleDebug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Snapchat APK
        run: wget -O snapchat.apk "$APK_URL"
        env:
          APK_URL: ${{ secrets.APK_URL }}

      - name: Download dexsearch
        run: wget -q -O dexsearch.jar "https://github.com/rodit/dexsearch/releases/download/$DEXSEARCH_VERSION/dexsearch-latest.jar"
        env:
          DEXSEARCH_VERSION: ${{ secrets.DEXSEARCH_VERSION }}

      - name: Download Android Platform
        run: wget -q -O android.zip "https://dl.google.com/android/repository/platform-32_r01.zip"
      - run: unzip -qq android.zip

      - name: Generate Bindings
        run: java -jar dexsearch.jar -i snapchat.apk -s snap.ds -o bindings.json -a "android-12/android.jar"

      - name: Publish Release APK and Bindings
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            app/build/outputs/apk/debug/app-debug.apk
            bindings.json
